### ISSUE TITLE
Fix Fortify Poor Logging Practice: Use of a System Output Stream Issue

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1113]
**Description**

To avoid having to explain future Fortify issues that are false positive or simply a bad practice. The preferable solution is to fix some of the false positive findings such that they will not appear in future Fortify runs.

This ticket is for fixing the false positives under the `Poor Logging Practice: Use of a System Output Stream` category.

**Risk Level**

Fortify lists this issue as a low risk.

**Goal**
- [x] Fix all of the bad practice issues that can be changed that fall under the `Poor Logging Practice: Use of a System Output Stream` category.

**Code Practice Suggestions**
In the future, avoid using `sys.stderr` and instead use Djangos `self.stderr`. See https://docs.djangoproject.com/en/3.1/topics/logging/

**Comment by bama4** [comment]
Test results (Failures do not appear to be related to these changes):

```
======================================================================
FAIL: test_invitations (siteapp.tests.GeneralTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 546, in test_invitations
    do_invitation(self.user2.email)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 515, in do_invitation
    self._accept_invitation(username)
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 373, in _accept_invitation
    self.assertRegex(self.browser.title, "Sign In")
AssertionError: Regex didn't match: 'Sign In' not found in 'Welcome to Compliance Automation - GovReady-Q'

======================================================================
FAIL: test_questions_module (siteapp.tests.QuestionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 1233, in test_questions_module
    do_submodule("My second answer.")
  File "/home/adangwa/REPOS/govready-q/siteapp/tests.py", line 1209, in do_submodule
    self.assertRegex(self.browser.title, "Next Question: Introduction")
AssertionError: Regex didn't match: 'Next Question: Introduction' not found in 'Next Question: module | Test The Module Question Types - GovReady-Q'

----------------------------------------------------------------------
Ran 63 tests in 364.902s

FAILED (failures=2)
```
