### ISSUE TITLE
The module question type tests fails on develop branch

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1181]
**Describe the bug as a Story**
The module question type tests fails on `develop` branch.

**To Reproduce**
1. `python manage.py test siteapp.tests.QuestionsTests.test_questions_module`

**Expected behavior**
Test passes

**Desktop (please complete the following information):**
 - OS: MacOS 14.14

## Acceptance criteria 

TEST WORKS OR IS CHANGED SO IT WORKS.

**Comment by gregelin** [comment]
Output:

```
$ python manage.py test siteapp.tests.QuestionsTests.test_questions_module
INFO: ALLOWED_HOSTS ['localhost']
INFO: Connection scheme is 'http'.
INFO: 'SITE_ROOT_URL' set to http://localhost:8000 
WARNING: Specified PDF generator is not supported. Setting generator to 'off'.
WARNING: Specified IMG generator is not supported. Setting generator to 'off'.
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
2020-12-12 14:31:07,253 siteapp.good_settings_helpers level ERROR login ip=127.0.0.1 username=me result=user:2
2020-12-12 14:31:07,282 siteapp.views level INFO {"user": {"id": 2, "username": "me"}, "event": "project_list"}
2020-12-12 14:31:08,442 siteapp.views level INFO {"user": {"id": 2, "username": "me"}, "event": "project_list"}
2020-12-12 14:31:12,844 siteapp.views level INFO {"object": {"task": "project", "id": 4, "title": "I want to answer some questions on Q. 3"}, "user": {"id": 2, "username": "me"}, "event": "start_app"}
2020-12-12 14:31:12,844 siteapp.views level INFO {"object": {"object": "project", "id": 3, "title": "I want to answer some questions on Q. 3"}, "user": {"id": 2, "username": "me"}, "event": "new_project"}
2020-12-12 14:31:12,846 siteapp.views level INFO {"object": {"object": "element", "id": 1, "name": "I want to answer some questions on Q. 3"}, "user": {"id": 2, "username": "me"}, "event": "new_element new_system"}
2020-12-12 14:31:12,860 siteapp.views level INFO {"object": {"object": "element", "id": 1, "name": "I want to answer some questions on Q. 3"}, "user": {"id": 2, "username": "me"}, "event": "new_element new_system assign_owner_permissions"}
2020-12-12 14:31:12,872 siteapp.views level INFO {"object": {"object": "system", "id": 1, "name": "I want to answer some questions on Q. 3"}, "user": {"id": 2, "username": "me"}, "event": "new_system assign_owner_permissions"}
change_answer() - self.click_element("#link-to-question-q_module a")
F
======================================================================
FAIL: test_questions_module (siteapp.tests.QuestionsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/codedata/code/govready-q-master/siteapp/tests.py", line 1251, in test_questions_module
    do_submodule("My second answer.")
  File "/codedata/code/govready-q-master/siteapp/tests.py", line 1230, in do_submodule
    self.assertRegex(self.browser.title, "Next Question: The Question")
AssertionError: Regex didn't match: 'Next Question: The Question' not found in 'Test The Module Question Types - GovReady-Q'

----------------------------------------------------------------------
Ran 1 test in 49.883s
```

**Comment by t-s** [comment]
Consider headless Selenium as one potential improvement

**Comment by t-s** [comment]
I believe currently depends on #1195

**Comment by gregelin** [comment]
Fixed
