### ISSUE TITLE
ImportError: cannot import name 'Context' from 'django.template.base'

### ISSUE THREAD

**Issue by t-s** [GovReady/govready-q#1195]
**Describe the bug as a Story**
CircleCI and my local environment on the `develop` branch produce an error with the description `ImportError: cannot import name 'Context' from 'django.template.base'`. This causes builds to fail. It seems to be related to a versioning issue with a package. Full traceback is posted below.

**To Reproduce**
1. Push current `develop` branch to CircleCI.

**Expected behavior**
I expect to be able to run the server both locally and in the CircleCI virtual environment.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 81
 - Virtual Machine? N/A
 - Screen size: N/A

 - As well as CircleCI

## Developer hints

When debugging issue locally, reverting to a previous `requirements.txt` resolved issue and allowed me to `runserver`.

## Acceptance criteria 

  GIVEN a push to CircleCI,
  WHEN the environment attempts to run the Django server,
  THEN the error displayed above should not occur and the server should run successfully.

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/t-s/code/develop/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/t-s/code/develop/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Users/t-s/code/develop/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/t-s/code/develop/env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/t-s/code/develop/env/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/t-s/code/develop/env/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/t-s/code/develop/env/lib/python3.8/site-packages/htmlemailer/__init__.py", line 2, in <module>
    from django.template.base import Template, Context
ImportError: cannot import name 'Context' from 'django.template.base' (/Users/t-s/code/develop/env/lib/python3.8/site-packages/django/template/base.py)```

**Comment by t-s** [comment]
[Failed CircleCI run](https://app.circleci.com/pipelines/github/GovReady/govready-q/1396/workflows/7555c35d-14a6-4b40-8e38-3c9455704718/jobs/3537)

**Comment by azharem** [comment]
Fixed this issue through a fork. [Branch can be viewed here](https://github.com/azharem/django-html-emailer/tree/fix/Context_import_error).  Changed importing Context from django base module to context module in `__init__.py` file.

**Comment by t-s** [comment]
@azharem 💯 Thanks! I contacted the package maintainer over slack and will submit a PR if I'm able. Can verify that fixes it, so a downstream incompatibility

**Comment by azharem** [comment]
> @azharem 💯 Thanks! I contacted the package maintainer over slack and will submit a PR to the package if I'm able. Can verify that fixes it, so a downstream incompatibility

@t-s  I created an issue as well [at maintainer's site here](https://github.com/govtrack/django-html-emailer/issues/5).

**Comment by t-s** [comment]
@azharem Excellent, thank you, I was just forking it myself

**Comment by t-s** [comment]
@azharem Go ahead and push a pull request for that branch if you don't mind

**Comment by azharem** [comment]
> @azharem Go ahead and push a pull request for that branch if you don't mind

Done. [Link for pull request](https://github.com/govtrack/django-html-emailer/pull/6).

**Comment by gregelin** [comment]
The original error is related to running Django 3.1.4. GovReady is working fine with Django 3.0.11. I'm rolling back to Django 3.0.11 for develop branch.  We should continue to watch this issue.

**Comment by gregelin** [comment]
Fixed
