### ISSUE TITLE
Fixing migration issue to 0.9.1.52 from older version - LINE 1: SELECT "controls_statement"."id", "controls_statement"."impo...

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1359]
The following are notes on resolving a data migration issue with older versions of GovReady to 0.9.1.50.2.

# About

It appears the existence of a special`history` related field in a database model (`Statement`) is effecting a database migration script that pre-dates the addition of the `history` related field. FIX: Temporarily comment out `history` related field from `Statement` model ( `controls/models.py`) and also change a line in relevant migration (NOTE: may not technically be necessary) and run migrations manually with `python3 manage.py migrate` . Then restore the `history` related field.

# The Error

If you receive the error:

```
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, controls, dbstorage, discussion, guardian, guidedmodules, notifications, sessions, siteapp, sites, socialaccount, system_settings
Running migrations:
  Applying controls.0032_auto_20201113_0458...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/govready-q/govready-q/controls/migrations/0032_auto_20201113_0458.py", line 33, in create_prototype_statements
    prototype.save()
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/models/base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/models/base.py", line 784, in save_base
    force_update, using, update_fields,
  File "/home/govready-q/.local/lib/python3.6/site-packages/django/db/models/base.py", line 847, in _save_table
    raise ValueError("Cannot force an update in save() with no primary key.")
ValueError: Cannot force an update in save() with no primary key.
```
...or the error...

```
  Applying controls.0032_auto_20201113_0458...Traceback (most recent call last):
psycopg2.errors.UndefinedColumn: column controls_statement.import_record_id does not exist
LINE 1: SELECT "controls_statement"."id", "controls_statement"."impo...
                                          ^

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/govready-q/govready-q/controls/migrations/0032_auto_20201113_0458.py", line 33, in create_prototype_statements
    prototype.save()
  File "/usr/local/lib/python3.6/dist-packages/simple_history/models.py", line 484, in post_save
    self.create_historical_record(instance, created and "+" or "~", using=using)
  File "/usr/local/lib/python3.6/dist-packages/simple_history/models.py", line 502, in create_historical_record
    attrs[field.attname] = getattr(instance, field.attname)
django.db.utils.ProgrammingError: column controls_statement.import_record_id does not exist
LINE 1: SELECT "controls_statement"."id", "controls_statement"."impo...
``` 

# The Fix

The following is a manual correction to successfully run the migrations. YOUR EXACT STEPS WILL VARY DEPENDING ON YOUR INSTALL.

```
su govready-q
cd /home/govready-q/govready-q
pip3 install --user django-simple-history
pip3 install --user filetype
pip3 install --user pyinstrument

# Edit controls/migrations/0032_auto_20201113_0458.py to omment out line #32 and save file
#
# # prototype.id = None
#
vim controls/migrations/0032_auto_20201113_0458.py

# Temporarily comment out line #64 in controls/models.py
# and save file
#
# # history = HistoricalRecords(cascade_delete_history=True)
#
vim controls/models.py 

# run migrations as govready-q
python3 manage.py migrate

# Edit controls/models.py and return line working and save file
#
# history = HistoricalRecords(cascade_delete_history=True)
#
vim controls/models.py 

# as root stop and start supervisor
service supervisor stop
service supervisor start
```

**Comment by davidpofo** [comment]
IF you look at the error django-simple-history is only having a problem
because there is an issue with the import record id not existing this makes
me think it is a migration issue with import records. `import_record_id
does not exist`. I am not so sure this fix is appropriate might need fix
the migration file and/or check if it is related to import_record_id
instead of providing this manual fix.
