### ISSUE TITLE
Docker version barfing on fresh install

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#298]
I am suddenly having trouble running the Docker version from a fresh install of govready-q-nightly.

Dockerized version comes up but then fails at last stage of `first_run.sh` script.

```
Gregs-MacBook-Pro:govreadydev2 greg$ docker container rm -f govready-q
govready-q
Gregs-MacBook-Pro:govreadydev2 greg$ ./docker_container_run.sh --sqlitedb /Users/greg/govreadydev2/govready-q-database.sqlite --appsdevdir /Users/greg/govreadydev2/apps --address localhost:8090 --image govready/govready-q-nightly 
Using default tag: latest
latest: Pulling from govready/govready-q-nightly
Digest: sha256:91228628d0c7378239202781cdb798c963cac8f31a1c8abf786117307639e1a9
Status: Image is up to date for govready/govready-q-nightly:latest
docker container run --detach --name govready-q -p 8090:8000 -e ADDRESS=localhost:8090 -e HTTPS=false -e DBURL= -e EMAIL_HOST= -e EMAIL_PORT= -e EMAIL_USER= -e EMAIL_PW= -e EMAIL_DOMAIN= --mount type=bind,src=/Users/greg/govreadydev2/govready-q-database.sqlite,dst=/usr/src/app/local/db.sqlite3 --mount type=bind,src=/Users/greg/govreadydev2/apps,dst=/mnt/apps govready/govready-q-nightly
GovReady-Q has been started!
Container Name: govready-q
Container ID: aa355f808fc3fd056452fe174864acb4d591cf3d951363efc9699eb1fb30dff2
URL: http://localhost:8090
Gregs-MacBook-Pro:govreadydev2 greg$ docker container exec -it govready-q ./first_run.sh
Installed 2 object(s) from 1 fixture(s)
Let's create your first Q user. This user will have superuser privileges in the Q administrative interface.
Username: amelia
Email address: amelia@govready.com
Password: 
Password (again): 
Superuser created successfully.
Let's create your Q organization.
Organization Name: OCTAE LINCS
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/siteapp/management/commands/first_run.py", line 29, in handle
    org = Organization.create(name=name, subdomain="main", admin_user=User.objects.filter(is_superuser=True).first())
  File "/usr/src/app/siteapp/models.py", line 263, in create
    org.get_organization_project().set_system_task("organization", admin_user)
  File "/usr/src/app/siteapp/models.py", line 575, in set_system_task
    module_name="app")
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
guidedmodules.models.DoesNotExist: Module matching query does not exist.
```

Then going to web page:

![screen shot 2017-10-26 at 4 32 14 pm](https://user-images.githubusercontent.com/24979/32075593-4d574124-ba6b-11e7-8a1e-061f1beea3d4.png)

**Comment by JoshData** [comment]
Fixed by 4d137627f6a9bbc6ffa58e46226ff50f19419a0c and e083db5bd043c42907b28c86aeefbf599a3d70cb.
