### ISSUE TITLE
export project data in branch ge-module-nav-0727 throwing error

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#678]
At least for (agency) IT System project. 

```
Internal Server Error: /projects/18/__export
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "./siteapp/views.py", line 952, in g
    return f(request, project)
  File "./siteapp/views.py", line 1007, in export_project
    data = project.export_json(include_metadata=True, include_file_content=True)
  File "./siteapp/models.py", line 801, in export_json
    for key, value in self.root_task.export_json(serializer).items():
  File "./guidedmodules/models.py", line 1382, in export_json
    build_dict)
  File "./siteapp/models.py", line 766, in serializeOnce
    ret = serialize_func()
  File "./guidedmodules/models.py", line 1354, in build_dict
    ("answers", build_answers()),
  File "./guidedmodules/models.py", line 1376, in build_answers
    a.export_json(ret, serializer)
  File "./guidedmodules/models.py", line 2064, in export_json
    value = self.get_value()
  File "./guidedmodules/models.py", line 1915, in get_value
    for t in self.answered_by_task.all()
  File "/usr/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 498, in __get__
    return self.related_manager_cls(instance)
  File "/usr/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 795, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
  File "./guidedmodules/models.py", line 1886, in __repr__
    return "<TaskAnswerHistory %s>" % (repr(self.taskanswer),)
  File "./guidedmodules/models.py", line 1575, in __repr__
    return "<TaskAnswer %s in %s>" % (repr(self.question), repr(self.task))
  File "/usr/lib64/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 175, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name)
django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist: TaskAnswer has no task.
[pid: 58|app: 0|req: 104/2544] 216.81.94.71 () {46 vars in 882 bytes} [Tue Jul 30 14:31:09 2019] POST /projects/18/__export => generated 27 bytes in 735 msecs (HTTP/1.1 500) 7 headers in 306 bytes (1 switches on core 0)
[pid: 61|app: 0|req: 1186/2545] 216.81.81.80 () {44 vars in 982 bytes} [Tue Jul 30 14:31:10 2019] GET /projects/8/cbp-it-system-richman => generated 138937 bytes in 419 msecs (HTTP/1.1 200) 8 headers in 460 bytes (1 switches on core 0)
```

**Comment by gregelin** [comment]
OBE
