### ISSUE TITLE
quickstart and populate data failing on validating raw type

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#728]
When `./quickstart.sh` creates test data (presumably using `populate`) and the questionnaire chosen is, the data provisioning crashes. 
```
Do you want to add some simulated starting data (users, a second organization, and assessments)? [y/n] y
Admin for Pulp Co: Melissa
Adding system...
web test client with host <pulp-co>
GET on: </store>
POST on: </store/govready-q-files-startpack/PTA-Demo>
Adding assessments...
web test client with host <pulp-co>
GET on: </projects>
GET on: </projects/4/demo-pta-for-information-collections-and-forms>
0 repeatable components
0 repeatable components, 0 non-completable components
Prepping assessments (tasks, pass #1)...
Handling task 2
Cannot answer question of type 'module-set'

Handling task 5

Filling assessments (tasks, pass #2)...
Handling task 2
Cannot answer question of type 'module-set'

Handling task 5

Handling task 6
Cannot answer question of type 'file'

Handling task 7

Handling task 8

Handling task 9

Handling task 10

Handling task 11
Cannot answer question of type 'multiple-choice'

Handling task 12

Handling task 13
Cannot answer question of type 'file'

Handling task 14
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/codedata/code/govready-q-0.8.6-sep/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/codedata/code/govready-q-0.8.6-sep/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/codedata/code/govready-q-0.8.6-sep/env/lib/python3.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/codedata/code/govready-q-0.8.6-sep/env/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/codedata/code/govready-q-0.8.6-sep/testmocking/management/commands/populate.py", line 58, in handle
    call_command('answer_all_tasks', '--quiet', '--impute', 'answer', '--org', org.subdomain)
  File "/codedata/code/govready-q-0.8.6-sep/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 141, in call_command
    return command.execute(*args, **defaults)
  File "/codedata/code/govready-q-0.8.6-sep/env/lib/python3.7/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/codedata/code/govready-q-0.8.6-sep/testmocking/management/commands/answer_all_tasks.py", line 38, in handle
    answer_randomly(task, halt_impute=halt_impute, skip_impute=skip_impute, quiet=options['quiet'])
  File "/codedata/code/govready-q-0.8.6-sep/testmocking/data_management.py", line 185, in answer_randomly
    value = validator.validate(question, answer)
  File "/codedata/code/govready-q-0.8.6-sep/guidedmodules/answer_validation.py", line 125, in validate
    validate_func = getattr(_class, "validate_" + question.spec["type"].replace("-", "_"))
AttributeError: type object 'validator' has no attribute 'validate_raw'
...
```

**Comment by gregelin** [comment]
@ethankaminski It is OK to skp this question type if easier.

**Comment by ethankaminski** [comment]
I've encountered this at times, but only very sporadically. I'm currently having trouble reproducing it on my end, as well (note: I'm using 0.9.0.dev, and have not migrated a 0.8.6 DB).

The fact that `raw` is not in the list of questions that are handled _should_, in theory, implicitly prevent `question.spec["type"]` from ever being that value, and thus, I don't see how this exception could be happening.

Of course, it IS happening, quite sporadically. Mitigations that come to mind are (a) add an explicit check to prevent this case, or (b) add more logging when an unexpected error occurs. I may go ahead and implement both, since it's quick to do, would mean we can fix this if it comes up again, and shouldn't have any real downside.

**Comment by gregelin** [comment]
OBE and container install.
