### ISSUE TITLE
(0.9.0) AppSource.DoesNotExist: AppSource matching query does not exist.

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#756]
What happened: I got a 500 error, '"AppSource.DoesNotExist: AppSource matching query does not exist", after migration from 0.8.6 to 0.9.0.rc-005.

What I expected: No 500 error. Not sure if button was enabled when it shouldn't have been, or there was a problem with the app sources, or what.

What I did:

* started with a fresh 0.8.6 instance
* ran quickstart.sh to populate
* invited a user test1 to one of the projects
* stopped the server, checkout'ed 0.9.0.rc-005, did the migration, restarted the server

App sources configured:
1 - - null source
2 - system - local filesystem at modules/system
3 - govready-q-files-startpack - local filesystem at q-files/vendors/govready/govready-q-files-startpack/q-files

I went to http://localhost:8000/store

I got the error "There are no AppSources configured by this site’s administrator that provide any apps, sorry!"

I clicked the "Create New Project" button anyway (it was not disabled).

The Create New Project popup appeared, and I filled it out, then clicked the "Create" button.

I got the error "Something went wrong, sorry."

webserver log:

```
Internal Server Error: /tasks/_authoring_tool/create-app-project
Traceback (most recent call last):
  File "/Users/kaminski/src/govready/govready-q/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/kaminski/src/govready/govready-q/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/kaminski/src/govready/govready-q/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/kaminski/src/govready/govready-q/env/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/Users/kaminski/src/govready/govready-q/guidedmodules/views.py", line 1074, in authoring_create_q
    new_q_appsrc = AppSource.objects.get(slug="govready-q-files-stubs")
  File "/Users/kaminski/src/govready/govready-q/env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/kaminski/src/govready/govready-q/env/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
guidedmodules.models.AppSource.DoesNotExist: AppSource matching query does not exist.
[08/Oct/2019 20:41:03] "POST /tasks/_authoring_tool/create-app-project HTTP/1.1" 500 19729
```

**Comment by gregelin** [comment]
App Sources have been configured, but in 0.9.0 there is an additional step to *publish* the apps that have been loaded into the database. The migration does not publish any apps. We could either update the documentation to include the step or adjust migration to publish the apps.

The create new project will not (currently) properly work on containerized version because local files cannot be written.

**Comment by ohsh6o** [comment]
Hi @gregelin, finally got around to testing this and encountered the same issue using `v0.9.1.47.1` from the [`govready-q-nightly:latest`](https://hub.docker.com/r/govready/govready-q-nightly) Docker image. Do you have recommendations on how I can PR modifications to your docs to make this more clear. I do not mind contributing!

**Comment by davidpofo** [comment]
@peterkaminski Is this addressed in docker?
